[package]
name = "l1reg_lp"
version = "0.1.0"
authors = ["convexbrain <convexbrain@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
totsu = {path = "../../solver_rust_conic"}
rand = "0.8.4"
itertools = "0.10.1"
rand_xoshiro = "0.6.0"
env_logger = "0.9.0"
plotters = "0.3.1"
