[package]
name = "svm_qp"
version = "0.1.0"
authors = ["convexbrain <convexbrain@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
totsu = {path = "../../solver_rust_conic", features = ["f64lapack"]}
utils = {path = "../utils"}
rand = "0.8.4"
rand_xoshiro = "0.6.0"
env_logger = "0.9.0"
plotters = "0.3.1"
num-traits = "0.2.14"

[dependencies.intel-mkl-src]
default-features = false
version = "0.6.0+mkl2020.1"
features = ["mkl-static-lp64-seq"]
#path = "../../../../others/intel-mkl-src/intel-mkl-src"
#features = ["mkl-static-lp64-iomp"]
