[package]
name = "utils"
version = "0.1.0"
authors = ["convexbrain <convexbrain@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
totsu = "0.9.1"
num-traits = "0.2.15"
plotters = "0.3.2"
log = "0.4.17"
