[workspace]

members = [
    "l1reg_lp",
    "svm_qp",
    "trajplan_qcqp",
    "toruscompl_socp",
    "partitioning_sdp",
    "imgnr_udef",
    
    "utils",
]

exclude = [
    "nostd_cortex-m",
]
