# https://crates.io/crates/mdbook

[book]
authors = ["convexbrain"]
language = "ja"
multilingual = false
src = "src"
title = "TotsuBook (ja)"

[build]
build-dir = "../docs/book"

[output.html]
mathjax-support = true
google-analytics = "UA-57046411-1"
git-repository-url = "https://github.com/convexbrain/Totsu"